backend:
  name: github
  repo: itzde15/my-fun-blog   # must match your username/repo exactly

media_folder: "images"
public_folder: "/images"

collections:

  - name: "football"
    label: "Football"
    folder: "posts/football"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "music"
    label: "Music"
    folder: "posts/music"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "comedy"
    label: "Comedy"
    folder: "posts/comedy"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
