backend:
  name: github
  repo: itzde15/my-fun-blog
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "posts"
    label: "Blog Posts"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"} 
